const loader = "imports-loader?imports=ulog&additionalCode=log=>ulog";
require(loader + "(\"artifact.js\")!./artifact.js");
require(loader + "(\"chat.js\")!./chat.js");;
require(loader + "(\"data_cache.js\")!./data_cache.js");
require(loader + "(\"debugging.js\")!./debugging.js");
require(loader + "(\"dialog.js\")!./dialog.js");
require(loader + "(\"entity_decode.js\")!./entity_decode.js");
require(loader + "(\"entity_info.js\")!./entity_info.js");
require(loader + "(\"extract_niantic_parameters.js\")!./extract_niantic_parameters.js");
require(loader + "(\"game_status.js\")!./game_status.js");
require(loader + "(\"hooks.js\")!./hooks.js");
require(loader + "(\"idle.js\")!./idle.js");
require(loader + "(\"location.js\")!./location.js");
require(loader + "(\"map_data_calc_tools.js\")!./map_data_calc_tools.js");
require(loader + "(\"map_data_debug.js\")!./map_data_debug.js");
require(loader + "(\"map_data_render.js\")!./map_data_render.js");
require(loader + "(\"map_data_request.js\")!./map_data_request.js");
require(loader + "(\"ornaments.js\")!./ornaments.js");
require(loader + "(\"panes.js\")!./panes.js");
require(loader + "(\"player_names.js\")!./player_names.js");
require(loader + "(\"portal_data.js\")!./portal_data.js");
require(loader + "(\"portal_detail.js\")!./portal_detail.js");
require(loader + "(\"portal_detail_display.js\")!./portal_detail_display.js");
require(loader + "(\"portal_detail_display_tools.js\")!./portal_detail_display_tools.js");
require(loader + "(\"portal_highlighter.js\")!./portal_highlighter.js");
require(loader + "(\"portal_info.js\")!./portal_info.js");
require(loader + "(\"portal_marker.js\")!./portal_marker.js");
require(loader + "(\"redeeming.js\")!./redeeming.js");
require(loader + "(\"region_scoreboard.js\")!./region_scoreboard.js");
require(loader + "(\"request_handling.js\")!./request_handling.js");
require(loader + "(\"search.js\")!./search.js");
require(loader + "(\"send_request.js\")!./send_request.js");
require(loader + "(\"smartphone.js\")!./smartphone.js");
require(loader + "(\"status_bar.js\")!./status_bar.js");
require(loader + "(\"utils_misc.js\")!./utils_misc.js");

import "./boot"