name: Tests
'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: 'Node.js LTS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - name: 'Cache node_modules'
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Run All Node.js Tests
        run: npm run test
